# Nombre del programa final
PROGRAMA := suma

# TODO 1
CC := gcc

# TODO 2
CFLAGS := -Wall

all: $(PROGRAMA)

# TODO 3
$(PROGRAMA): suma.c
	$(CC) $(CFLAGS) suma.c -o $(PROGRAMA)

# TODO 4
clean:
	rm -f $(PROGRAMA)

.PHONY: all clean
